# Generated by Django 6.0.5 on 2026-07-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_daraz_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('khalti', 'Khalti'), ('esewa', 'eSewa'), ('card', 'Credit / Debit Card'), ('fonepay', 'Fonepay')], default='cod', max_length=10),
        ),
    ]
